export const STORE_CLASSES = 'STORE_CLASSES'
export const STORE_DEFAULT_TIME = 'STORE_DEFAULT_TIME'
export const STORE_STUDENTS = 'STORE_STUDENTS'
export const STORE_INSTRUCTOR_ID = 'STORE_INSTRUCTOR_ID'