# Generated by Django 2.2.4 on 2019-08-31 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_code', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.Instructor')),
                ('students', models.ManyToManyField(blank=True, to='users.Student')),
            ],
        ),
    ]
