# Generated by Django 2.2.4 on 2019-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='classes_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classes_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
