# Generated by Django 2.2.4 on 2019-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190902_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_currently_holding_attendance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
